### ISSUE TITLE
"An error has occured in the target for an activation"

### ISSUE THREAD

**Issue by Skrubbadubba** [maybeclean/musicbee-rich-presence#10]
After i install the plugin, it is disabled in MB. After i click enable, that message is shown. I have tried both the latest version, and v1.1.

Worth noting is that it was enabled the first time i installed it (latest ver), but discord didnt show anything, so i re-enabled it or re-installed it (dont remember which one). Then this happend.

**Comment by maybeclean** [comment]
Feel free to try again with the latest binaries, make sure the dependencies aswell.
