### ISSUE TITLE
Discord not recognizing Musicbee (Failed artwork upload)

### ISSUE THREAD

**Issue by bomberzx** [maybeclean/musicbee-rich-presence#12]
my plugin is well installed on Musicbee with the ID yet Discord dosn't show musicbee as rich presence. I eventually get this error in Musicbee:
![image](https://user-images.githubusercontent.com/57452855/130436172-1bdc01a1-5200-4fb0-9100-ddf962dfdb34.png)

**Comment by Incognymous** [comment]
I have the same issue as well.

**Comment by maybeclean** [comment]
This issue should've been solved in 1.2.5 / 9149e3f.
