### ISSUE TITLE
Rich Presence not working

### ISSUE THREAD

**Issue by ShadowOTC** [maybeclean/musicbee-rich-presence#13]
I really don't know why, but mine isn't working.
I created the aplication on Discord, added the .PNGs for play/pause, copied the AppID and inserted in MusicBee,
restarted and i'm not getting any errors but still the Rich Presence doesn't show up.
I've seen that kanjis can be problematic, but i tested with safe titles and still doesn't appear.
Discord Stable 94599 - MusicBee 3.4.7805 - Windows 10
Any help?
![image](https://user-images.githubusercontent.com/47579857/130800350-7e8c315c-6013-4a82-b7b6-fd26e3312475.png)

**Comment by maybeclean** [comment]
Feel free to try again with the latest binaries.
