### ISSUE TITLE
Stuck at "Playing at 6%"

### ISSUE THREAD

**Issue by jericjan** [maybeclean/musicbee-rich-presence#15]
When I hover over the playing/paused icon, I can see that it says "playing at 6%" no matter what. 

![screenshott](https://i.imgur.com/mn42SUj.png)

Also, what happens when it reaches the 300 image limit. Does the plugin remove old assets or does it just break?

**Comment by maybeclean** [comment]
Once you hit the 300 asset limit the plugin will still work but only for currently uploaded artworks, if an artwork isn't uploaded Discord will catch it when uploading and just fail it.

The "Playing at X%" refers to your current volume in MusicBee, tested it on my end and it seems to be working fine. Does it just not update volume for you on the pop-up?

*Asset limit was actually 150 not that long ago so hopefully Discord decides to bump it up again.
