### ISSUE TITLE
401 Unauthorized when artwork uploads

### ISSUE THREAD

**Issue by KBxR** [maybeclean/musicbee-rich-presence#3]
when it tries to upload artwork, it gives an error saying
`Log Entry : 12:17:12 AM Saturday, May 15, 2021
 : {"message": "401: Unauthorized", "code": 0}`

**Comment by maybeclean** [comment]
Binaries have been updated, let me know if you still have authorization issues
https://github.com/maybeclean/musicbee-rich-presence/releases/tag/v1.1

**Comment by KBxR** [comment]
Hi, still having the same error

`Log Entry : 12:27:13 PM Saturday, May 15, 2021
 : {"message": "401: Unauthorized", "code": 0}`
