### ISSUE TITLE
Still getting "Exception has been thrown by the target of an invocation."

### ISSUE THREAD

**Issue by Graydenn** [maybeclean/musicbee-rich-presence#5]
I see you've closed this issue, but I'm still getting it. I've followed your steps, there are .ldb files in `%appdata%\discord\Local Storage\leveldb`, and I am logged into Discord.

![](https://fk.ci/2Rysf2T.png)

**Comment by KBxR** [comment]
are you using the precompiled binaries?

**Comment by AllyTheFox** [comment]
> are you using the precompiled binaries?

I am also getting the "Exception has been thrown by the target of an invocation" and I am using the precompiled binaries.

**Comment by Graydenn** [comment]
Whoops, saw this and forgot to reply right after I woke up. Yeah, I'm using the precompiled release.

**Comment by KBxR** [comment]
the pre compiled binaries are out of date and for some reason they havent updated them, i have a fork with it working if you wanna use that in the mean time [link](https://github.com/KBxR/musicbee-rich-presence)

**Comment by MsNecromancer** [comment]
> the pre compiled binaries are out of date and for some reason they havent updated them, i have a fork with it working if you wanna use that in the mean time [link](https://github.com/KBxR/musicbee-rich-presence)

Ah, wonderful and it also has auto-updating albums.

**Comment by KBxR** [comment]
does the artwork uploading work for you w/o errors? If so, that's weird. I still get errors

**Comment by MsNecromancer** [comment]
> does the artwork uploading work for you w/o errors? If so, that's weird. I still get errors

Very weird, because yes it uploads without errors.  The application takes a while to update the image but that is just how the Dev portal is.

**Comment by maybeclean** [comment]
Looking at the above it is more than likely a dependency issue for alot of people, i used [ILRepack](https://github.com/gluck/il-repack) which was supposed to package all dependency dlls into one "master" dll for simpler installation but it seems like that has been causing issues for people.

If you have issues with uploading artwork it could very well be that for some reason the DiscordToken class in Util.cs is unable to grab your auth token from your local files. You can manually get your auth token and replace [Line 50](https://github.com/maybeclean/musicbee-rich-presence/blob/master/mb_DiscordRichPresence.cs#L50) with your manually saved token if you experience that issue.

I have been using this for roughly around a year now and around a couple months for a Tidal project that also uses roughly the same code to upload and show artwork.

I'll be included all dependency dlls in releases from now on just to ensure theres no issue with that part.

**Comment by KBxR** [comment]
i dont have any "token"'s in any of my ldb files, is there a way to force it to give one?

**Comment by maybeclean** [comment]
Closing this because of it being months old. If you still have problems feel free to reopen an issue.
