### ISSUE TITLE
Failed to grab auth token

### ISSUE THREAD

**Issue by 3obz** [maybeclean/musicbee-rich-presence#7]
Keep getting failed to grab auth token whenver I launch Musicbee after putting in my Developer App ID. *Using Canary Build 92599 (f88ba3e) with the new precompiled binaries*

![image](https://user-images.githubusercontent.com/86505125/128452472-01063ea2-0f7c-4b65-9bff-987972ca8e72.png)

**Comment by maybeclean** [comment]
Current builds only support Stable Discord, pushing an update to the precompiled binaries and commits to the repo to support both PTB and Canary in a couple of minutes. You'll need to select your version in preferences. 
![image](https://user-images.githubusercontent.com/49769124/128456836-cea7eba3-3edf-4675-a0c9-be6f454973cd.png)

**Comment by maybeclean** [comment]
Updated Binaries should be uploaded now, if you're still having any issues let me know.

**Comment by omar-abdelbari** [comment]
Thank you, but it seems like I'm still getting the error "failed to grab auth token" after choosing the Canary release and it keeps getting reset to the Stable release everytime upon starting it *if there's anyway I can send you some logs to make your life easier let me know*
![image](https://user-images.githubusercontent.com/86505125/128485646-715b3117-ee49-4351-a025-5d7a57dac310.png)
![image](https://user-images.githubusercontent.com/86505125/128486272-19c4a509-fd3a-4ce0-be06-67fd994b3823.png)

**Comment by maybeclean** [comment]
The _Unauthorized_ in logs is because the grabber couldn't get your auth token and prove that your account was the one which was attempting to do authorized requests to the app (upload endpoint in this case)

The dropdown resetting to stable should be fine as long as your config file (C:\MusicBee-RichPresence\configuration.ini) contains `DiscordType = 3` which targets Discord Canary

Just to make sure, do you have a `%appdata%\discordcanary\Local Storage\leveldb` folder? If you do, inside there should be .ldb files with random numbers which hold some information about your discord session like your auth key. Formatting does differ between versions but i tested it against PTB and Canary and it seemed to work on my end.

Anyways, i'll be expanding logging in the grabber to see whats going on. New binaries should be available in a few minutes.

**Comment by omar-abdelbari** [comment]
> The dropdown resetting to stable should be fine as long as your config file (C:\MusicBee-RichPresence\configuration.ini) contains DiscordType = 3 which targets Discord Canary

It was showing DiscordType=1 so I did change it manually to 3 but that didn't seem to fix the issue and I'm still getting 
 : {"message": "401: Unauthorized", "code": 0}

> Just to make sure, do you have a %appdata%\discordcanary\Local Storage\leveldb folder? If you do, inside there should be .ldb files with random numbers which hold some information about your discord session like your auth key. Formatting does differ between versions but i tested it against PTB and Canary and it seemed to work on my end.

Yes I did check that earlier and these are the contents of my leveldb folder 
![image](https://user-images.githubusercontent.com/86505125/128580095-f592c67c-1e99-4041-a4dc-bc2036cddda8.png)

Thank you so much for your help either way and I will make sure to clean my plugin folder in case there's any plugin incompatibility that's causing this issue also I forgot to say that but I'm using Discord Canary with Powercord installed so I'm also going to try a fresh installation of Vanilla Canary without any modding to narrow it down for you and make it easier in case it's just Powercord doing something weird.

**Comment by omar-abdelbari** [comment]
Also That's quite irrelevant and not that important but the .bat file in the binaries will only work if you have installed Musicbee for the current user only but if you have installed it for all users the paths should be 
copy "%~dp0\mb_DiscordRichPresence.dll" "C:\Program Files (x86)\MusicBee\Plugins\mb_DiscordRichPresence.dll"
copy "%~dp0\Newtonsoft.Json.dll" "C:\Program Files (x86)\MusicBee\Plugins\Newtonsoft.Json.dll"
copy "%~dp0\win32-discord-rpc.dll" "C:\Program Files (x86)\MusicBee\Plugins\win32-discord-rpc.dll" and it should be set to run as adminstrator

It's not that important and I'm sure most github users at least know how to edit a .bat file but I thought I would let you know if you want to add one.

**Comment by maybeclean** [comment]
Changed the bat file in the new release to target program files, thanks.

Other than that i restructured the token grabber from the latest commit, hopefully that should fix your issue. Feel free to try with the new binaries.

**Comment by omar-abdelbari** [comment]
Thank you once again and as I told you I cleaned up my entire plugin library and even tried running the stable release of discord and changing it to the Stable release in the plugin settings and also made sure it's DiscordType = 1 in the configuration file yet I'm still getting the same error message in the logs so at this point I'm not really sure what could be causing this. *thinking about running it through a VM to check if it's something with my PC acting up*
![image](https://user-images.githubusercontent.com/86505125/128584557-ba9c0563-c032-4d6f-a7f9-6d460293b8ba.png)

**Comment by maybeclean** [comment]
Closing this issue because its over a week old, if you still need help feel free to open a _new_ issue.
