### ISSUE TITLE
album art not showing

### ISSUE THREAD

**Issue by coolcoleman** [maybeclean/musicbee-rich-presence#8]
hi so i installed this through the install.bat and the album covers arent showing. however the play and pause buttons are. is there a way to fix this https://imgur.com/xj3fDCA

**Comment by maybeclean** [comment]
Discord takes a bit to cache your album arts when you first upload them, by now if everything was successful they should be working. Check here under RichPresence -> Assets https://discord.com/developers/applications/

**Comment by coolcoleman** [comment]
oh i didnt know i was supposed to upload them manually. do i just upload them here https://imgur.com/HUIAQCb ? does the name of the file matter? does the type of image matter (png/jpeg)? image size?

**Comment by maybeclean** [comment]
Bad wording on my part, the plugin automates uploads for you. They still need to be cached on Discord's side and that takes roughly a couple of minutes depending on their current server load.

You can check your logs at C:\MusicBee-RichPresence\log.txt and a successful asset upload should look like this:

![Image](https://i.imgur.com/6UyiG9B.png)

**Comment by coolcoleman** [comment]
oh sweet thank you :-)
