### ISSUE TITLE
rich presence doesn't work after installation of the plugin

### ISSUE THREAD

**Issue by bomberzx** [maybeclean/musicbee-rich-presence#9]
musicbee managed to install the plugin correctly with the right id app but the rich presence on discord doesn't work at all
![image](https://user-images.githubusercontent.com/57452855/128750842-5860f8c5-3d7d-4935-8cb0-814eb1a532c5.png)
![image](https://user-images.githubusercontent.com/57452855/128750854-f2a6bc10-7ddb-4ebf-81b7-fe603893f99b.png)

**Comment by maybeclean** [comment]
Looks like you manually added MusicBee for Discord to show as playing. Thats not needed and you can remove it in `Discord Settings -> Activity Status`

**Comment by bomberzx** [comment]
> Looks like you manually added MusicBee for Discord to show as playing. Thats not needed and you can remove it in `Discord Settings -> Activity Status`

I removed it now there's just nothing at all
